//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lugo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decision
    {
        public int DecisionId { get; set; }
        public int UserId { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
