//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lugo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Index
    {
        public int IndexId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> WaterId { get; set; }
        public System.DateTime Data { get; set; }
        public int IndexOld { get; set; }
        public int IndexNew { get; set; }
        public Nullable<int> IndexDiff { get; set; }
        public int IndexMonth { get; set; }
        public int IndexYear { get; set; }
        public string Description { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual SysWaterType SysWaterType { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
