//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lugo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Index
    {
        public int IndexId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Data { get; set; }
        public int IndexOldBaieRece { get; set; }
        public int IndexNewBaieRece { get; set; }
        public Nullable<int> IndexDiffBaieRece { get; set; }
        public int IndexOldBaieCalda { get; set; }
        public int IndexNewBaieCalda { get; set; }
        public Nullable<int> IndexDiffBaieCalda { get; set; }
        public int IndexOldBucatarieRece { get; set; }
        public int IndexNewBucatarieRece { get; set; }
        public Nullable<int> IndexDiffBucatarieRece { get; set; }
        public int IndexOldBucatarieCalda { get; set; }
        public int IndexNewBucatarieCalda { get; set; }
        public Nullable<int> IndexDiffBucatarieCalda { get; set; }
        public int IndexMonth { get; set; }
        public int IndexYear { get; set; }
        public string Description { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
