//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lugo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysWaterType
    {
        public SysWaterType()
        {
            this.Index = new HashSet<Index>();
        }
    
        public int WaterId { get; set; }
        public string WaterName { get; set; }
    
        public virtual ICollection<Index> Index { get; set; }
    }
}
