//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lugo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Complain = new HashSet<Complain>();
            this.Decision = new HashSet<Decision>();
            this.UserInfo = new HashSet<UserInfo>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
            this.Index = new HashSet<Index>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Complain> Complain { get; set; }
        public virtual ICollection<Decision> Decision { get; set; }
        public virtual ICollection<UserInfo> UserInfo { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
        public virtual ICollection<Index> Index { get; set; }
    }
}
